#include <glm.hpp>

// Gráficos
#include "Mesh.h"
#include "Renderer.h"
#include "Texture.h"
#include "Camera.h"
#include "Light.h"
#include "Shader.h"
#include "BufferObjects.h"
// Físicas
#include "ParticleSystem.h"
#include "Rigid.h"
#include "Collider.h"
#include "Muelle.h"
#include "Liquido.h"
#include "Articulacion.h"
#include "PhysicsSystem.h"
#include "ForceGenerator.h"
// Audio
#include "Audio.h"
#include "AudioSource.h"
#include "AudioManager.h"
// Core
#include "Entity.h"
#include "Game.h"
#include "Scene.h"
#include "ResourceManager.h"
#include "InputManager.h"
// UI y Editor
#include "UI/Button.h"
#include "UI/Text.h"
#include "UI/Canvas.h"
#include "UI/Editor.h"
// Otros
#include "Terreno.h"
#include "MeshLoader.h"
#include "Utils.h"

//#include <glew.h>
#include <freeglut.h>